crm/api/urls.py
from django.conf.urls import include
from django.urls import path
from .views import HealthCheck, TochkaCallback, RunSomeTask

# app_name = 'api'

urlpatterns = [
    path('health/', HealthCheck.as_view(), name='health'),
    path('v1/banks/tochka/callback/', TochkaCallback.as_view(),
         name='tochka_callback'),
    path('v1/run_some_task/', RunSomeTask.as_view(),
         name='run_some_task'),
]

crm/apps/blog/urls.py
from django.urls import path, re_path
from . import views

app_name = 'blog'

urlpatterns = [
    re_path('(?P<article_type>[\w-]+)/(?P<slug>[\w-]+)/$',
            views.ArticleDetailView.as_view(), name='detail'),

    re_path('(?P<article_type>[\w-]+)/$',
            views.ArticleListView.as_view(), name='list'),
]

crm/apps/landing/urls.py
from django.urls import path
from . import views

app_name = 'landing'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('kontakty/', views.ContactsView.as_view(), name='contacts'),
]

crm/apps/blog/models.py
from django.db import models
from django.utils import timezone

from organization.models import Organization
from ckeditor.fields import RichTextField


class Article(models.Model):

    ARTICLES = 'articles'
    NEWS = 'news'

    ARTICLE_TYPE_CHOICES = (
        (ARTICLES, 'Статьи'),
        (NEWS, 'Новости'),
    )

    organization = models.ForeignKey(
        Organization, verbose_name='Организация', on_delete=models.SET_NULL,
        null=True, blank=True)
    article_type = models.CharField(
        max_length=8, verbose_name='Тип', default=ARTICLES,
        choices=ARTICLE_TYPE_CHOICES)
    title = models.CharField(max_length=200, verbose_name='Заголовок')
    slug = models.SlugField()
    content = RichTextField(verbose_name='Контент')
    published = models.DateTimeField(verbose_name='Дата публикации',
                                     default=timezone.now)
    updated = models.DateTimeField(auto_now=True,
                                   verbose_name='Дата изменения')
    views_number = models.PositiveIntegerField(
        verbose_name='Количество просмотров', default=0)

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'
        ordering = ('-published',)

    def __str__(self):
        return self.title

    @classmethod
    def get_article_type_name(cls, type_: str) -> str:
        return dict((k, v) for k, v in cls.ARTICLE_TYPE_CHOICES).get(type_)

    def get_absolute_url(self):
        return ''

crm/apps/blog/views.py
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView


from .models import Article


class ArticleDetailView(DetailView):
    model = Article
    template_name = 'blog/detail.html'

    def get_object(self, queryset=None):
        obj = super().get_object(queryset=queryset)
        obj.views_number += 1
        obj.save()
        return obj


class ArticleListView(ListView):
    model = Article
    template_name = 'blog/list.html'

    def get_queryset(self):
        qs = super().get_queryset()
        article_type = self.kwargs['article_type']
        qs = qs.filter(article_type=article_type)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['article_type_name'] = Article.get_article_type_name(
            self.kwargs['article_type'])
        return context

crm/templates/blog/detail.html
{% extends 'base.html' %}
{% block title %}{{ article.title }}{% endblock %}
{% block description %}
    Статьи, новости о робототехнике, Уфа, Затон, Михайловка
{% endblock %}
{% block extra_head %}
    <!-- Put this script tag to the <head> of your page -->
    <script type="text/javascript" src="https://vk.com/js/api/openapi.js?162"></script>

    <script type="text/javascript">
        VK.init({apiId: 7129753, onlyWidgets: true});
    </script>


{% endblock %}

{% block content %}

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'landing:index' %}">Главная</a></li>
            <li class="breadcrumb-item"><a href="{% url 'blog:list' article_type=article.article_type %}">{{ article.get_article_type_display }}</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ article.title }}</li>
        </ol>
    </nav>


    <h1>{{ article.title }}</h1>

    {{ article.content|safe }}
    <br>
    <!-- Put this div tag to the place, where the Comments block will be -->
    <div id="vk_comments"></div>
    <script type="text/javascript">
        VK.Widgets.Comments("vk_comments", {limit: 15, attach: "*"});
    </script>

{% endblock %}

crm/templates/blog/list.html
{% extends 'base.html' %}

{% block title %}{{ article_type_name }}{% endblock %}

{% block description %}
    Список статей новостей о робототехнике
{% endblock %}
{% block content %}


    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'landing:index' %}">Главная</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ article_type_name }}</li>
        </ol>
    </nav>

    <h1>{{ article_type_name }}</h1>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">Заголовок</th>
            <th scope="col">Просмотры</th>
        </tr>
        </thead>
        <tbody>
        {% for article in article_list %}
            <tr>
                <td><a
                        href="{% url 'blog:detail' article_type=article.article_type slug=article.slug %}"
                >{{ article.title }}</a></td>
                <td>{{ article.views_number }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}