crm/api/urls.py
from django.conf.urls import include
from django.urls import path
from .views import HealthCheck, TochkaCallback, RunSomeTask

# app_name = 'api'

urlpatterns = [
    path('health/', HealthCheck.as_view(), name='health'),
    path('v1/banks/tochka/callback/', TochkaCallback.as_view(),
         name='tochka_callback'),
    path('v1/run_some_task/', RunSomeTask.as_view(),
         name='run_some_task'),
]

crm/apps/dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('payments', views.PaymentStatView.as_view(), name='payment_stat'),
    path('lessons', views.LessonListView.as_view(), name='lesson_list'),
    path('lessons/<pk>', views.LessonDetailView.as_view(),
         name='lesson_detail'),
]

crm/apps/landing/urls.py
from django.urls import path
from . import views

app_name = 'landing'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('kontakty/', views.ContactsView.as_view(), name='contacts'),
]

crm/apps/private/urls.py
from django.urls import path
from . import views

app_name = 'private'

urlpatterns = [
    path('', views.PrivateIndexView.as_view(), name='index'),
    path('season_ticket/list', views.PrivateSeasonTicketListView.as_view(),
         name='season_ticket_list'),
    path('season_ticket/paid/<season_ticket_pk>',
         views.SeasonTicketPaidView.as_view(),
         name='season_ticket_paid'),

    path('lessons', views.PrivateLessonListView.as_view(),
         name='lesson_list'),
    path('lessons/detail/<lesson_pk>', views.PrivateLessonDetailView.as_view(),
         name='lesson_detail'),
]

crm/apps/tariff/urls.py
from django.urls import path
from . import views

app_name = 'tariff'

urlpatterns = [
    path('abonement/', views.TariffListView.as_view(),
         name='tariff_list'),
    path('opisanie/', views.CourseListView.as_view(),
         name='course_list'),

    path('abonementy/kupit/<tariff_pk>',
         views.SeasonTicketCreateView.as_view(),
         name='season_ticket_create'),

]

crm/templates/_cookie_modal.html
<script>
    $(document).ready(function () {
        //if cookie hasn't been set...
        if (document.cookie.indexOf("cookiePolicyShown=true")<0 & (window.location.href.indexOf("{% url 'privacy' %}") <0) ) {
            console.log(window.location.href );
            $("#cookieDialog").show();
            //Modal has been shown, now set a cookie so it never comes back
            $("#cookieModalClose").click(function () {
                $("#cookieDialog").hide();
                document.cookie = "cookiePolicyShown=true; expires=Fri, 31 Dec 9999 23:59:59 GMT; path=/";

            });
        }
    });
</script>


<nav class="navbar fixed-bottom navbar-light bg-light" id="cookieDialog" style="display: none">
    <div class="small col-md-10">Мы используем файлы «cookies» и похожие технологии на нашем веб-сайте, чтобы улучшить работу и повысить эффективность сайта.
        <br>Используя этот сайт, Вы соглашаетесь с размещением cookie-файлов на Вашем компьютере в соответствии с условиями <a href="{% url 'privacy' %}">политики конфиденциальности.</a></div>
    <div class="col-md-2">
        <a href="" class="btn btn-success btn-sm" data-dismiss="modal" id="cookieModalClose">Я согласен(-на)</a>
    </div>
</nav>

crm/templates/_login_social.html
{% if not request.user.is_authenticated %}
    <div class="text-center">
        {% if not without_alert %}
            <div class="alert alert-primary" role="alert">
                <h5> Для быстрой связи с Вами зарегистрируйтесь на сайте с помощью одной из соцсетей:</h5>
            </div>
        {% endif %}

    <p> Войти с помощью внешнего аккаунта:</p>
        <a title="Google" class="socialaccount_provider google btn btn-danger" role="button" href="/accounts/google/login/?process=login">Google</a>

        <a title="VK" class="socialaccount_provider vk btn btn-info" role="button"  href="/accounts/vk/login/?process=login">&nbsp;&nbsp;&nbsp; VK &nbsp;&nbsp;&nbsp;</a>

        <a title="Facebook" class="socialaccount_provider facebook btn btn-primary" role="button"  href="/accounts/facebook/login/?process=login">Facebook</a>

    </div>
{% endif %}

crm/templates/_nav.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <!-- logo png -->
    <a class="navbar-brand" href="/">
        <img src="{% static 'robot.svg' %}" alt="logo">
    </a>
    <!-- end logo png -->
    <a class="navbar-brand" href="/">Лаборатория роботов</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            {#                  <li class="nav-item active">#}
            {#                    <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>#}
            {#                  </li>#}

            <li class="nav-item {% if '/kursy' in request.build_absolute_uri and  'abonement' not in request.build_absolute_uri%} active {% endif %}">
                <a class="nav-link" href="{% url 'tariff:course_list' %}">Курсы</a>
            </li>

            <li class="nav-item {% if '/abonement' in request.build_absolute_uri %} active {% endif %}">
                <a class="nav-link" href="{% url 'tariff:tariff_list' %}">Абонементы</a>
            </li>

            <li class="nav-item {% if '/prepodavateli' in request.build_absolute_uri %} active {% endif %}">
                <a class="nav-link" href="{% url 'organization:instructor_list' %}">Преподаватели</a>
            </li>

            <li class="nav-item {% if '/kontakty' in request.build_absolute_uri %} active {% endif %}">
                <a class="nav-link" href="{% url 'landing:contacts' %}">Контакты</a>
            </li>

            {#      <li class="nav-item">#}
            {#        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>#}
            {#      </li>#}

            <li class="nav-item">
                <a class="nav-link {% if '/private' in request.build_absolute_uri %} active {% endif %}" href="{% url 'private:season_ticket_list' %}">Личный кабинет</a>
            </li>

{#            <li class="nav-item">#}
{#                <a class="nav-link {% if '/raspisanie' in request.build_absolute_uri %} active {% endif %}" href="{% url 'timetable:current_month' %}">Расписание</a>#}
{#            </li>#}

        </ul>

        {% if not request.user.payment_set %}
            <a href="/polls/zapis-na-probnoe-zanyatie/" class="btn btn-success quadrat" role="button" style="margin-right: 1em" >Пробное занятие</a>
        {% endif %}

    {% if request.user.is_superuser %}
        <a href="{% url 'dashboard:index' %}" class="btn btn-info" role="button" style="margin-right: 1em">CRM</a>
    {% endif %}
        {% if not user.is_active %}
            <a href="{% url 'account_login' %}" class="btn btn-outline-primary my-sm-0" role="button">Вход</a>
        {% else %}
            <a href="{% url 'account_logout' %}" class="btn btn-outline-secondary my-sm-0" role="button">Выход</a>
        {% endif %}

    </div>
</nav>

crm/templates/_social_buttons.html
<style>
    .fab {
        padding: 0px;
        font-size: 25px;
        width: 30px;
        text-align: center;
        text-decoration: none;
    }

    .fab:hover {
        opacity: 0.7;
    }

    .btn-fb {
        background: #3B5998;
        color: white;
    }

    .btn-vk {
        background: #4a76a8;
        color: white;
    }

    .btn-ins {
        background: #e1306c;
        color: white;
    }

</style>

<a class="btn btn-vk" href="https://vk.com/robocraftlab" target="_blank">
    <i class="fab fa-vk"></i>
</a>

<a class="btn btn-ins" href="https://www.instagram.com/robocraftlab" target="_blank">
    <i class="fab fa-instagram"></i>
</a>

<a class="btn btn-fb" href="https://www.facebook.com/robocraftlab" target="_blank">
    <i class="fab fa-facebook-f"></i>
</a>

crm/templates/base.html
{% load static %}
{% load tz_detect %}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">

    <link rel="icon" href="{% static 'favicons/favicon.png' %}" type="image/png">
    <link rel="apple-touch-icon" sizes="32x32" href="{% static 'favicons/favicon-32.png' %}">
    <link rel="apple-touch-icon" sizes="64x64" href="{% static 'favicons/favicon-64.png' %}">
    <link rel="apple-touch-icon" sizes="128x128" href="{% static 'favicons/favicon-128.png' %}">
    <link rel="apple-touch-icon" sizes="512x512" href="{% static 'favicons/favicon-512.png' %}">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <!-- Bootstrap core CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    {#    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.9/css/mdb.min.css" rel="stylesheet">#}

    {% if not debug %}
        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=UA-148572939-1"></script>
        <script>
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());

            gtag('config', 'UA-148572939-1');
        </script>

        <meta name="yandex-verification" content="9d5542c90800a145" />
        <!-- Yandex.Metrika counter -->
        <script type="text/javascript" >
            (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
                m[i].l=1*new Date();k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
            (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

            ym(55326454, "init", {
                clickmap:true,
                trackLinks:true,
                accurateTrackBounce:true,
                webvisor:true
            });
        </script>
        <noscript><div><img src="https://mc.yandex.ru/watch/55326454" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
        <!-- /Yandex.Metrika counter -->


    {% endif %}

    {% block extra_head %}
    {% endblock extra_head %}

    <title>{% block title %}Лаборатория роботов  - школа робототехники и программирования{% endblock title %}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="Description" content="{% block description %}Курсы робототехники и программирования в Уфимском районе{% endblock %}">
    <meta name="Keywords" content="{% block keywords %}Робототехника, программирование, школа, курсы, Уфа, Михайловка, Затон, Суровка, Алексеевка, Дмитриевка, Уфимский район {% endblock %}">


    <style>
        @media (min-width:768px) {
            .navhome {
                padding-right: 50px;
            }
        }

        .navbar {
            text-align: center;
        }

        .container-fluid {
            display: inline-block;
        }
    </style>
</head>

<body>

{% block nav %}
    {% include '_nav.html' %}
{% endblock %}

<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-md-9">
            <br>
            {% for m in messages %}
                <div class="alert alert-{{ m.tags|default:'danger' }} alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    {{ m }}
                </div>
            {% endfor %}

            {% block content %}
            {% endblock content %}
        </div>
    </div>
</div>

<!-- Footer -->
{% block footer %}
<hr>
<footer class="page-footer font-small blue">

    <div class="footer-copyright text-center py-3">
        {% include '_social_buttons.html' %}

        <br>
        © {% now "Y" %}
        <a href="https://robocraftlab.ru">RoboCraftLab.ru</a><br>
        <a href="{% url 'privacy' %}" class="small">Политика конфиденциальности</a>
        {#        <script type='text/javascript'>#}
        {#            (function () {#}
        {#                window['yandexChatWidgetCallback'] = function() {#}
        {#                    try {#}
        {#                        window.yandexChatWidget = new Ya.ChatWidget({#}
        {#                            guid: '48cfa6b6-2f97-4e1e-9a44-ff8f2e4011f0',#}
        {#                            buttonText: 'Ответим на ваши вопросы',#}
        {#                            title: 'Чат',#}
        {#                            theme: 'light',#}
        {#                            collapsedDesktop: 'never',#}
        {#                            collapsedTouch: 'always'#}
        {#                        });#}
        {#                    } catch(e) { }#}
        {#                };#}
        {#                var n = document.getElementsByTagName('script')[0],#}
        {#                    s = document.createElement('script');#}
        {#                s.async = true;#}
        {#                s.charset = 'UTF-8';#}
        {#                s.src = 'https://chat.s3.yandex.net/widget.js';#}
        {#                n.parentNode.insertBefore(s, n);#}
        {#            })();#}
        {#        </script>#}
    </div>

</footer>
<!-- Footer -->
{% endblock %}

<!-- JQuery -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
<!-- MDB core JavaScript -->
{#<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.9/js/mdb.min.js"></script>#}

{% include '_cookie_modal.html' %}
{% tz_detect %}

{% block extra_js %}
{% endblock %}
</body>
</html>