crm/api/urls.py
from django.conf.urls import include
from django.urls import path
from .views import HealthCheck, TochkaCallback, RunSomeTask

# app_name = 'api'

urlpatterns = [
    path('health/', HealthCheck.as_view(), name='health'),
    path('v1/banks/tochka/callback/', TochkaCallback.as_view(),
         name='tochka_callback'),
    path('v1/run_some_task/', RunSomeTask.as_view(),
         name='run_some_task'),
]

crm/apps/landing/urls.py
from django.urls import path
from . import views

app_name = 'landing'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('kontakty/', views.ContactsView.as_view(), name='contacts'),
]

crm/apps/private/urls.py
from django.urls import path
from . import views

app_name = 'private'

urlpatterns = [
    path('', views.PrivateIndexView.as_view(), name='index'),
    path('season_ticket/list', views.PrivateSeasonTicketListView.as_view(),
         name='season_ticket_list'),
    path('season_ticket/paid/<season_ticket_pk>',
         views.SeasonTicketPaidView.as_view(),
         name='season_ticket_paid'),

    path('lessons', views.PrivateLessonListView.as_view(),
         name='lesson_list'),
    path('lessons/detail/<lesson_pk>', views.PrivateLessonDetailView.as_view(),
         name='lesson_detail'),
]

crm/apps/tariff/urls.py
from django.urls import path
from . import views

app_name = 'tariff'

urlpatterns = [
    path('abonement/', views.TariffListView.as_view(),
         name='tariff_list'),
    path('opisanie/', views.CourseListView.as_view(),
         name='course_list'),

    path('abonementy/kupit/<tariff_pk>',
         views.SeasonTicketCreateView.as_view(),
         name='season_ticket_create'),

]

crm/apps/tariff/models.py
import random
import string
from decimal import Decimal

from ckeditor.fields import RichTextField
from django.db import models
from django.db.models.functions import Concat
from django.contrib.contenttypes.models import ContentType
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils.timezone import now, localtime

from core.models import User
from organization.models import Organization
from payment.models import Payment


class Section(models.Model):
    organization = models.ForeignKey(
        Organization, verbose_name='Организация', on_delete=models.CASCADE)
    name = models.CharField('Название раздела', max_length=120)
    sorting_number = models.PositiveIntegerField('Номер по порядку')
    description = RichTextField(verbose_name='Описание')

    class Meta:
        verbose_name = 'Раздел'
        verbose_name_plural = 'Разделы'
        ordering = ['sorting_number']

    def __str__(self):
        return self.name


class Course(models.Model):
    organization = models.ForeignKey(
        Organization, verbose_name='Организация', on_delete=models.CASCADE)
    section = models.ForeignKey(
        Section, verbose_name='Раздел', on_delete=models.SET_NULL, null=True,
        blank=True)
    name = models.CharField('Название курса', max_length=120)
    sorting_number = models.PositiveIntegerField('Номер по порядку')
    description = RichTextField(verbose_name='Описание')
    updated = models.DateTimeField('Обновлен', auto_now=True)

    class Meta:
        verbose_name = 'Курс'
        verbose_name_plural = 'Курсы'
        ordering = ['sorting_number']

    def __str__(self):
        return self.name


class Tariff(models.Model):

    LESSON_DURATION_HOUR = 2

    course = models.ForeignKey(Course, on_delete=models.CASCADE,
                               verbose_name='Курс')
    name = models.CharField('Название', max_length=100)
    is_active = models.BooleanField(blank=True, default=True)
    cost = models.PositiveIntegerField('Стоимость')
    lesson_count = models.PositiveIntegerField('Количество занятий')
    expiration_date = models.PositiveIntegerField('Срок действия в днях')
    updated = models.DateTimeField('Обновлен', auto_now=True)

    class Meta:
        verbose_name = 'Тариф'
        verbose_name_plural = 'Тарифы'

    def __str__(self):
        return f'{self.name} {self.course}'

    def get_hour_num(self):
        return int(self.lesson_count * self.LESSON_DURATION_HOUR)

    def get_hour_cost(self):
        return int(self.cost/self.lesson_count/self.LESSON_DURATION_HOUR)

    def get_season_ticket_name(self):
        return self.__str__()


class SeasonTicketWithLessonsManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().annotate(
            lesson_count=models.Count('studentonlesson')).\
            filter(lesson_count__gte=0)


class SeasonTicket(models.Model):
    CODE_LENGTH = 11
    seller = models.ForeignKey(User, verbose_name='Продавец',
                               on_delete=models.SET_NULL, blank=True, null=True,
                               related_name='seller')
    buyer = models.ForeignKey(User, verbose_name='Покупатель',
                              on_delete=models.SET_NULL, blank=True, null=True,
                              related_name='buyer')
    tariff = models.ForeignKey(
        Tariff, verbose_name='Тариф', on_delete=models.CASCADE)

    expiration_date = models.DateField('Дата окончания', blank=True, null=True)
    code = models.CharField('Код', max_length=CODE_LENGTH, unique=True,
                            null=True)
    student = models.ForeignKey(User, on_delete=models.SET_NULL,
                                null=True,
                                verbose_name='Обучаемый',
                                related_name='student',)
    discount = models.PositiveIntegerField(
        'Скидка', default=0,
        validators=[MinValueValidator(0), MaxValueValidator(100)])
    comment = models.TextField('Коментарий', blank=True, null=True)
    created = models.DateTimeField('Дата покупки', auto_now_add=True, )
    updated = models.DateTimeField('Дата обновления', auto_now=True, )

    class Meta:
        verbose_name = 'Абонемент'
        verbose_name_plural = 'Абонементы'
        ordering = ('-created', )

    def __str__(self):
        return f'{self.student} {self.tariff}'

    @property
    def owner(self):
        return self.student

    @property
    def cost(self):
        return Decimal(self.tariff.cost - self.tariff.cost * self.discount / 100) \
            if self.discount else self.tariff.cost
    cost.fget.short_description = 'Стоимость'

    def generate_code(self):
        rnd_nums = ''.join(
            random.choice(string.digits) for _ in range(self.CODE_LENGTH-3))
        return f'{self.tariff.course.organization.id}-{rnd_nums}'

    def save(self, *args, **kwargs):
        if not self.code:
            self.code = self.generate_code()
        super(SeasonTicket, self).save(*args, **kwargs)

    @property
    def payment_sum(self):
        payments_sum = Payment.objects.filter(
            content_type=ContentType.objects.get_for_model(self),
            object_id=self.id, status=Payment.PAID).aggregate(
            models.Sum('amount')
        )
        return payments_sum['amount__sum'] or 0

    @property
    def debt(self) -> bool:
        return self.cost - self.payment_sum

    debt.fget.short_description = 'Долг'

    @property
    def lesson_balance(self):
        from lesson.models import StudentOnLesson
        now_date = localtime(now())
        end_lesson_count = (
            StudentOnLesson.objects
            .annotate(
                lesson_datetime_end=Concat(
                    'lesson__date', models.Value(' '), 'lesson__time_end',
                    output_field=models.CharField()))
            .filter(season_ticket=self,
                    lesson_datetime_end__lt=str(now_date))).count()
        return self.tariff.lesson_count - end_lesson_count
    lesson_balance.fget.short_description = 'Осталось уроков'


class Confidant(models.Model):
    season_ticket = models.ForeignKey(SeasonTicket, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user}'

    class Meta:
        verbose_name = 'Довереное лицо'
        verbose_name_plural = 'Довереные лица'

crm/apps/tariff/forms.py
from django import forms
# from django.urls import reverse_lazy


class SeasonTicketOrderForm(forms.Form):
    comment = forms.CharField(
        label='Комментарий:',
        widget=forms.Textarea, max_length=100, required=False)

crm/apps/tariff/views.py
import logging
from django.contrib.auth.decorators import login_required

from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.utils.decorators import method_decorator
from django.views.generic import ListView, TemplateView

from organization.models import Organization
from payment.mixins import PaidSeasonTicketMixin

from .forms import SeasonTicketOrderForm
from .models import Course, Tariff, SeasonTicket


logger = logging.getLogger('crm')


class ListViewHeadMixin(ListView):

    def head(self, *args, **kwargs):
        last_tariff = self.get_queryset().latest('updated')
        response = HttpResponse('')
        # RFC 1123 date format
        response['Last-Modified'] = last_tariff.updated.strftime(
            '%a, %d %b %Y %H:%M:%S GMT')
        return response


class TariffListView(ListViewHeadMixin):
    template_name = 'tariff/tariff_list.html'
    context_object_name = 'tariffs'
    queryset = Tariff.objects.filter(cost__gt=0).order_by('course', 'cost')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['organization'] = Organization.objects.first()
        return context


class CourseListView(ListViewHeadMixin):
    template_name = 'tariff/course_list.html'
    context_object_name = 'courses'
    queryset = Course.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['organization'] = Organization.objects.first()
        return context


class SeasonTicketCreateView(PaidSeasonTicketMixin, TemplateView):
    template_name = 'tariff/season_ticket_create.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tariff'] = get_object_or_404(Tariff, id=kwargs['tariff_pk'],
                                              cost__gt=0)
        context['organization'] = Organization.objects.first()
        return context

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        context['form'] = SeasonTicketOrderForm()
        return self.render_to_response(context)

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        tariff = context['tariff']
        org = Organization.objects.first()

        form = SeasonTicketOrderForm(request.POST)
        if form.is_valid() and org.sb_test_mode:
            data = form.cleaned_data
            season_ticket = SeasonTicket.objects.create(
                tariff=tariff,
                buyer=request.user,
                comment=data['comment']
            )
            return self.paid_season_ticket(request, season_ticket,
                                           data['comment'])

        context['form'] = form
        return self.render_to_response(context)

crm/templates/tariff/_buy_season_ticket_message.html
<div class="card text-center">
  <div class="card-header">

  </div>
  <div class="card-body">
    <h5 class="card-title">Для покупки абонемента необходимо согласовать время посещений по телефону:</h5>
      <p class="card-text"> <a href="tel:+79639008998" class="btn btn-primary">+7 (963) 900 89 98</a></p>
      <p>после этого Вы сможете оплатить абонемент картой онлайн в <a href="{% url 'private:index' %}">личном кабинете</a></p>

  </div>
  <div class="card-footer text-muted">

  </div>
</div>

crm/templates/tariff/course_list.html
{% extends 'base.html' %}
{% block title %}Описание курсов{% endblock %}
{% block keywords %}Курсы, описание, Lego, программирование, робототехника, Уфа, Затон, Михайловка, Суровка, Алексеевка{% endblock %}
{% block content %}

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'landing:index' %}">Главная</a></li>
            <li class="breadcrumb-item active" aria-current="page">Курсы</li>
        </ol>
    </nav>

    <h1>Описание курсов</h1>

    {% for course in courses %}
        <div class="card" style="margin-top: 1em">
            <div class="card-header">
                <h2>{{ course.section.name }}. {{ course.name }}</h2>
            </div>
            <div class="card-body">
                {{ course.description|safe }}
            </div>
        </div>
    {% endfor %}
{% endblock %}

crm/templates/tariff/season_ticket_create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title %}
    Купить абонемент "{{ tariff.get_season_ticket_name }}"
{% endblock %}

{% block description %}
    Продажа абонементов на курсы
{% endblock %}

{% block content %}

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'landing:index' %}">Главная</a></li>
            {#            <li class="breadcrumb-item" aria-current="page">#}
            {#                <a href="{% url 'tariff:course_list' %}">Курсы</a>#}
            {#            </li>#}
            <li class="breadcrumb-item" aria-current="page">
                <a href="{% url 'tariff:tariff_list' %}">Абонементы</a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">
                Купить абонемент "{{ tariff.get_season_ticket_name }}"
            </li>
        </ol>
    </nav>

    {% if not seasonticket.tariff.organization.sb_test_mode %}
        {% include 'tariff/_buy_season_ticket_message.html' %}
    {% else %}

    <h1>Купить абонемент "{{ tariff.get_season_ticket_name }}"</h1>



        {% if form %}
            <p>Количестов часов: <b>{{ tariff.get_hour_num }}</b></p>
            <p>Стоимость часа: <b>{{ tariff.get_hour_cost }} руб.</b> </p>

            <form method="post">
                {% csrf_token %}
                {% for field in form %}
                    {% bootstrap_field field placeholder=''%}
                {% endfor %}



                <div class="form-group form-check">
                    <input type="checkbox" class="form-check-input" id="offerAgreementCheck"
                           required>
                    <label class="form-check-label" for="offerAgreementCheck">Я принимаю условия <a href="{{ organization.offer_agreement }}">договора оферты</a><br></label>
                </div>
                <b>К оплате: {{ tariff.cost }} рублей</b><br><br>


                {#        {% if not user.is_authenticated %}#}

                {#        {% else %}#}
                <div>
                    <button type="submit" class="btn btn-primary">Оплатить банковской картой </button><br>
                </div>
                {#        {% endif %}#}

                <small class="text-muted">Необходимо <a href="{% url 'account_login' %}">авторизоваться</a> на сайте<br></small>


                <p><small>
                    Для оплаты (ввода реквизитов Вашей карты) Вы будете перенаправлены на платёжный шлюз ПАО СБЕРБАНК. Соединение с платёжным шлюзом и передача информации осуществляется в защищённом режиме с использованием протокола шифрования SSL. В случае если Ваш банк поддерживает технологию безопасного проведения интернет-платежей Verified By Visa, MasterCard SecureCode, MIR Accept, J-Secure для проведения платежа также может потребоваться ввод специального пароля.
                    Настоящий сайт поддерживает 256-битное шифрование. Конфиденциальность сообщаемой персональной информации обеспечивается ПАО СБЕРБАНК. Введённая информация не будет предоставлена третьим лицам за исключением случаев, предусмотренных законодательством РФ. Проведение платежей по банковским картам осуществляется в строгом соответствии с требованиями платёжных систем МИР, Visa Int., MasterCard Europe Sprl, JCB.
                </small></p>
            </form>
        {% endif %}
    {% endif %}

{% endblock %}

crm/templates/tariff/season_ticket_paid.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load humanize %}

{% block title %}
    Купить абонемент "{{ tariff.get_season_ticket_name }}"
{% endblock %}

{% block description %}
    Продажа абонементов на курсы
{% endblock %}

{% block content %}

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'private:index' %}">Личный кабинет</a></li>
            <li class="breadcrumb-item active" aria-current="page">
                Оплатить абонемент
            </li>
        </ol>
    </nav>

    <h1>Оплатить абонемент</h1>
    <h5>{{ seasonticket.tariff.get_season_ticket_name }}</h5>
{#    <p>Количестов часов: <b>{{ seasonticket.tariff.get_hour_num }}</b></p>#}
{#<p>Стоимость часа: <b>{{ seasonticket.tariff.get_hour_cost }} руб.</b> </p>#}
    <p>Стоимость: <b>{{ seasonticket.tariff.cost|intcomma }}  руб.</b> {% if seasonticket.discount %} - скидка {{ seasonticket.discount }}% {% endif %}
    </p>




        <form method="post">
            {% csrf_token %}

                {% for field in form %}
                {% bootstrap_field field placeholder=''%}
            {% endfor %}

            <div class="form-group form-check">
                <input type="checkbox" class="form-check-input" id="offerAgreementCheck"
                       required>
                <label class="form-check-label" for="offerAgreementCheck">Я принимаю условия <a href="{{ organization.offer_agreement }}">договора оферты</a><br></label>
            </div>
            <b>К оплате: {{ seasonticket.debt|intcomma }} рублей</b><br><br>

            <div>
                <button type="submit" class="btn btn-primary">Оплатить банковской картой </button><br>
            </div>

            <small class="text-muted">Необходимо <a href="{% url 'account_login' %}">авторизоваться</a> на сайте<br></small>


            <p><small>
                Для оплаты (ввода реквизитов Вашей карты) Вы будете перенаправлены на платёжный шлюз ПАО СБЕРБАНК. Соединение с платёжным шлюзом и передача информации осуществляется в защищённом режиме с использованием протокола шифрования SSL. В случае если Ваш банк поддерживает технологию безопасного проведения интернет-платежей Verified By Visa, MasterCard SecureCode, MIR Accept, J-Secure для проведения платежа также может потребоваться ввод специального пароля.
                Настоящий сайт поддерживает 256-битное шифрование. Конфиденциальность сообщаемой персональной информации обеспечивается ПАО СБЕРБАНК. Введённая информация не будет предоставлена третьим лицам за исключением случаев, предусмотренных законодательством РФ. Проведение платежей по банковским картам осуществляется в строгом соответствии с требованиями платёжных систем МИР, Visa Int., MasterCard Europe Sprl, JCB.
            </small></p>
        </form>

{% endblock %}

crm/templates/tariff/tariff_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Купить абонемент{% endblock %}
{% block keywords %}Абонемент, курсы, робототехника, купить, цена, стоимость, оплатить, Уфа, Михайловка, Затон{% endblock %}

{% block content %}

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'landing:index' %}">Главная</a></li>
            <li class="breadcrumb-item active" aria-current="page">Абонементы</li>
        </ol>
    </nav>

    <h1>Абонементы</h1>

    <h5>Способы оплаты:</h5>

    <p><u>Банковской картой</u></p>
    <p>Для выбора оплаты товара с помощью банковской карты на соответствующей странице необходимо нажать кнопку Оплата заказа банковской картой. Оплата происходит через ПАО СБЕРБАНК с использованием банковских карт следующих платёжных систем:</p>
    <ul>
        <li>МИР <img src="{% static 'сс/mir.png' %}"></li>
        <li>VISA International <img src="{% static 'сс/visa.png' %}"></li>
        <li>Mastercard Worldwide <img src="{% static 'сс/mastercard.png' %}"></li>
        <li>JCB <img src="{% static 'сс/jcb.png' %}"></li>
    </ul>
    <small>* Продолжительность одного занятия 2 академических часа</small>
    <div class="row">
        {% for tariff in tariffs %}
            <div class="col-md-4" style="margin-top: 1em">
                <div class="card">
                    <div class="card-header">

                        <h5 class="text-center">
                            {% with ''|center:tariff.course.sorting_number as range %}
                                {% for  _ in range %}
                                    <i class="fa fa-star" style="color: forestgreen"></i>
                                {% endfor %}
                            {% endwith %}
                            {{ tariff.name }}

                        </h5>
                    </div>
                    <div class="card-body">
                        <h1 class="card-title pricing-card-title text-center"><small class="text-muted">{{ tariff.cost }}  руб.</small></h1>
                        <a href="{% url 'tariff:course_list' %}"><h6 class="card-subtitle mb-2 text-center">{{ tariff.course.name }}</h6></a>

                        <ul class="list-unstyled mt-3 mb-4">
                            <li>Количество часов: {% widthratio tariff.lesson_count 1 2 %}</li>
                            <li>Цена за час: <b>{{ tariff.get_hour_cost }} руб.</b></li>
                        </ul>
                        <a href="{% url 'tariff:season_ticket_create' tariff.id %}" class="nav-link">
                            <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
                        </a>
                    </div>
                </div>
            </div>

        {% endfor %}
    </div>
    <br>
    <div class="alert alert-info" role="alert">
        <div class="text-center"><a href="{{ organization.offer_agreement }}">Договор оферта</a></div>
    </div>


{% endblock %}