crm/api/urls.py
from django.conf.urls import include
from django.urls import path
from .views import HealthCheck, TochkaCallback, RunSomeTask

# app_name = 'api'

urlpatterns = [
    path('health/', HealthCheck.as_view(), name='health'),
    path('v1/banks/tochka/callback/', TochkaCallback.as_view(),
         name='tochka_callback'),
    path('v1/run_some_task/', RunSomeTask.as_view(),
         name='run_some_task'),
]

crm/apps/landing/urls.py
from django.urls import path
from . import views

app_name = 'landing'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('kontakty/', views.ContactsView.as_view(), name='contacts'),
]

crm/apps/poll/urls.py
from django.urls import path
from . import views

app_name = 'poll'

urlpatterns = [
    path('<slug:slug>/', views.PollView.as_view(), name='detail'),
    path('', views.PollListView.as_view(), name='list'),
]

crm/apps/poll/models.py
from django.db import models

from organization.models import Organization


class Poll(models.Model):
    organization = models.ForeignKey(
        Organization, verbose_name='Организация', on_delete=models.SET_NULL,
        null=True, blank=True)
    title = models.CharField(max_length=100, verbose_name='Заголовок')
    slug = models.SlugField()
    post_button_text = models.CharField(
        default='Отправить', max_length=50,
        verbose_name='Текст на кнопке отправки')
    is_active = models.BooleanField(verbose_name='Активен', default=True)
    email = models.EmailField('Отправлять ответы на email', blank=True,
                              null=True)
    created = models.DateTimeField(auto_now_add=True,
                                   verbose_name='Дата создания')

    def __str__(self):
        return self.title

    @property
    def poll_name(self):
        return f'{self.organization}-{self.title}'

    class Meta:
        verbose_name = 'Опрос'
        verbose_name_plural = 'Опросы'

    def get_post_num(self):
        required_question = Question.objects.\
            filter(is_required=True, poll=self).first()
        posts = Answer.objects.\
            filter(question=required_question).count()
        return posts


class Question(models.Model):

    TEXT = 'text'
    STRING = 'char'
    CHOICE = 'choice'
    INTEGER = 'integer'
    PHONE = 'phone'

    FIELD_TYPE_CHOICES = (
        (STRING, 'Строка'),
        (TEXT, 'Текст'),
        (CHOICE, 'Один из списка'),
        (INTEGER, 'Число'),
        (PHONE, 'Номер телефона'),
    )

    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
    question_text = models.CharField(max_length=255,
                                     verbose_name='Текст вопроса')
    field_type = models.CharField(max_length=20, verbose_name='Тип поля ввода',
                                  choices=FIELD_TYPE_CHOICES,
                                  default=STRING)
    field_data = models.CharField(max_length=255, blank=True, null=True,
                                  verbose_name='Данные поля')
    is_unique = models.BooleanField(verbose_name='Уникальный ответ',
                                    default=False)
    is_required = models.BooleanField(verbose_name='Обязательный ответ',
                                      default=True)

    sort_num = models.PositiveIntegerField(
        verbose_name='Порядок',
        help_text='Порядок расположения полей формы (сверху вниз)',
        default=1)

    def __str__(self):
        return self.question_text

    class Meta:
        verbose_name = 'Вопрос'
        verbose_name_plural = 'Вопросы'
        ordering = ('poll', 'sort_num')


class Answer(models.Model):
    session = models.CharField(max_length=32, verbose_name='Сессия')
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer_text = models.CharField(max_length=255, verbose_name='Текст ответа')
    created = models.DateTimeField(auto_now_add=True,
                                   verbose_name='Дата создания')

    def __str__(self):
        return self.answer_text

    class Meta:
        verbose_name = 'Ответ'
        verbose_name_plural = 'Ответы'

crm/apps/poll/forms.py
from typing import Type

from django import forms

from utils.validators import validate_phone_number

from .models import Question, Poll


POLL_FIELD_PREFIX = 'question-'


def poll_factory_form(poll: Poll) -> Type[forms.Form]:

    fields = {}

    for question in poll.question_set.all().order_by('sort_num'):
        init_kwargs = {
            'label': question.question_text + ':',
            'required': question.is_required
        }
        field_name = f'{POLL_FIELD_PREFIX}{question.id}'

        if question.field_type == Question.CHOICE:
            field = forms.ChoiceField
            init_kwargs.update({
                'choices': [
                    (val, val) for val in question.field_data.split(',')
                ] if question.field_data else None
            })

        elif question.field_type == Question.TEXT:
            field = forms.CharField
            init_kwargs.update({
                'widget': forms.Textarea
            })

        elif question.field_type == Question.PHONE:
            field = forms.CharField
            init_kwargs.update({
                'validators': [validate_phone_number]
            })

        elif question.field_type == Question.INTEGER:
            field = forms.IntegerField

        else:
            field = forms.CharField

        if not field:
            raise ValueError

        fields[field_name] = field(**init_kwargs)

    form_class: Type[forms.Form] = type('QuestionForm', (forms.Form,), fields)
    return form_class

crm/apps/poll/views.py
import datetime

from django.conf import settings
from django.db import transaction
from django.shortcuts import render, get_object_or_404
from django.template.loader import render_to_string
from django.views import View
from django.views.generic.list import ListView

from utils.sendgrid.client import send_message
from .models import Poll, Question, Answer
from .forms import poll_factory_form, POLL_FIELD_PREFIX


class UniqueAnswerAlreadyExists(Exception):
    pass


class PollView(View):
    template_name = 'poll/detail.html'

    def get(self, request, slug, *args, **kwargs):
        if hasattr(request, 'session') and not request.session.session_key:
            request.session.save()
            request.session.modified = True

        poll = get_object_or_404(Poll, slug=slug)
        form = poll_factory_form(poll)
        return render(
            request,
            self.template_name,
            {'poll': poll, 'form': form}
        )

    @staticmethod
    def _create_answer_obj(question_id: int,
                           answer: str,
                           session: str) -> Answer:
        # todo отрефакторить - сделать проверку одним
        #  запросом а не для каждого ответа по запросу
        question = Question.objects.get(id=question_id)
        if question.is_unique and Answer.objects.filter(
                question=question, answer_text=answer).exists():
            raise UniqueAnswerAlreadyExists
        if answer:
            return Answer(
                session=session,
                question=question,
                answer_text=answer
            )

    @staticmethod
    def send_answer_to_email(title: str, email: str, data: dict):
        dt = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
        subject = f'Ответ на "{title}" от {dt}'
        message = render_to_string(
            'poll/email_msg.html',
            {'data': data}
        )
        send_message(settings.DEFAULT_FROM_EMAIL, [email], subject, message)

    def post(self, request, slug, *args, **kwargs):
        poll = get_object_or_404(Poll, slug=slug)
        form = poll_factory_form(poll)
        session_key = request.session.session_key

        form = form(request.POST)
        error = None
        email_data, send_email = {'answers': []}, True
        if form.is_valid():
            try:
                with transaction.atomic():
                    answer_objects = []
                    for k, v in form.cleaned_data.items():
                        email_data['answers'].append(v)
                        if k.startswith(POLL_FIELD_PREFIX):
                            question_id = int(k.split('-')[1])
                            answer_obj = self._create_answer_obj(
                                question_id, v, session_key)
                            if answer_obj:
                                answer_objects.append(answer_obj)
                    Answer.objects.bulk_create(answer_objects)
            except UniqueAnswerAlreadyExists:
                error = 'Вы уже оставляли заявку'
                send_email = False

            if poll.email and send_email:
                email_data['user'] = request.user
                email_data['session_key'] = session_key
                self.send_answer_to_email(poll.title, poll.email, email_data)

            return render(request, 'poll/success.html', {'error': error})

        return render(request, self.template_name, {'poll': poll, 'form': form})


class PollListView(ListView):
    model = Poll
    template_name = 'poll/list.html'

crm/templates/poll/detail.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block title %}
    {{ poll.title }}
{% endblock %}

{% block description %}
    Опрос, голосование, {{ poll.title }}
{% endblock %}

{% block extra_head %}

    <!-- Put this script tag to the <head> of your page -->
    <script type="text/javascript" src="https://vk.com/js/api/openapi.js?162"></script>

    <script type="text/javascript">
        VK.init({apiId: 7129753, onlyWidgets: true});
    </script>


{% endblock %}

{% block content %}

{#    {% if messages %}#}
{#        <div>#}
{#            <strong>Messages:</strong>#}
{#            <ul>#}
{#                {% for message in messages %}#}
{#                    <li>{{message}}</li>#}
{#                {% endfor %}#}
{#            </ul>#}
{#        </div>#}
{#    {% endif %}#}

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'landing:index' %}">Главная</a></li>
            <li class="breadcrumb-item"><a href="{% url 'poll:list' %}">Опросы</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ poll.title }}</li>
        </ol>
    </nav>


    <h2 class="text-center">{{ poll.title }}</h2>

    <form method="post">{% csrf_token %}


        {% for field in form %}
            {% bootstrap_field field placeholder=''%}
        {% endfor %}


        <button type="submit" class="btn btn-primary">{{ poll.post_button_text }}</button>
    </form>
    <p></p>
    <!-- Put this div tag to the place, where the Comments block will be -->
    <div id="vk_comments"></div>
    <script type="text/javascript">
        VK.Widgets.Comments("vk_comments", {limit: 15, attach: "*"});
    </script>
{% endblock %}

crm/templates/poll/email_msg.html
{% for a in data.answers %}
    {{ a }}
{% endfor %}

{{ data.user }}

{{ data.session_key }}

---

crm/templates/poll/list.html
{% extends 'base.html' %}
{% block title %}Опросы, голосования{% endblock %}
{% block description %}
    Опросы
{% endblock %}

{% block content %}

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'landing:index' %}">Главная</a></li>
            <li class="breadcrumb-item active" aria-current="page">Опросы</li>
        </ol>
    </nav>

    <h1>Опросы</h1>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">Заголовок</th>
            <th scope="col">Ответы</th>
        </tr>
        </thead>
        <tbody>
        {% for poll in poll_list %}
            <tr>
                <td><a href="{% url 'poll:detail' slug=poll.slug %}">{{ poll.title }}</a></td>
                <td>{{ poll.get_post_num }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

crm/templates/poll/success.html
{% extends 'base.html' %}
{% block title %}
    Спасибо за ответы
{% endblock %}
{% block description %}
    Результаты опроса
{% endblock %}
{% block content %}

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'landing:index' %}">Главная</a></li>
            <li class="breadcrumb-item active" aria-current="page"><a href="{% url 'poll:list' %}">Опросы</a></li>
        </ol>
    </nav>

    <div class="text-center">
    {% if error %}
        <div class="alert alert-info" role="alert">            Вы уже оставляли заявку.
    {% else %}
        <div class="alert alert-success" role="alert">            Спасибо!
    {% endif %} Мы свяжемся с Вами в ближайшее время. </div>

{% include '_login_social.html' %}

{% endblock %}